Feat/footer
rodiontazetdinov/lubimovka pull request #3
Opened 2022-06-06 18:32 UTC by AvaveryU

2022-06-08 06:33 UTC, olgalatkina commented on index.html
> +        </div>
- начиная с ширины экрана 608 до 768 снизу очень большой отступ
- с ширины 768 до 1440 контент приклеен к низу экрана
- с ширины 1440 снова очень большой отступ снизу

2022-06-08 06:41 UTC, olgalatkina commented on index.html
> +                    <!--третий список -->
начиная с ширины 608 до 1439 список приклеен к правому краю экрана
![2Y_footer-608-right](https://user-images.githubusercontent.com/41871155/172549178-a9186de0-e9d3-4a4b-8fea-ed82cea6ed03.jpg)

2022-06-08 07:19 UTC, olgalatkina commented on index.html
> +    <footer class="footer">
до 1439 размер шрифта для мобилок и 3 колонки выглядят довольно странно))
![2Y_footer-1439](https://user-images.githubusercontent.com/41871155/172555143-f593cd99-448b-42db-a54f-51609b4e661f.jpg)

может раньше сделать вёрстку как на 1440?
или сделать промежуточный вариант, на 1200 получается так:
![Slice 1](https://user-images.githubusercontent.com/41871155/172555256-1a3277fd-d40c-4366-822f-39fb58f06fc8.png)
видно, что есть возможность сделать такую вёрстку на меньших ширинах экрана

2022-06-08 07:46 UTC, olgalatkina requested changes
На случай атомной войны на бэкграунд стоит кинуть цвет фона: background-color: var(--background); заодно потренировать css-переменные))
Тут, кстати, вылезает ещё одна проблемка, что футер не на всю ширину экрана. Ограничивает контент по ширине обычно контейнер внутри футера. Но это точно на твоё усмотрение!

Очень не гибкое решение с размерами логотипов, если потом заменят спонсоров или поменяют местами, то вёрстка полетит. 

Не прописаны ховеры на ссылках.

2022-06-12 22:07 UTC, AvaveryU commented on index.html
> +    <footer class="footer">
исправлено - футер выглядит на протяжении всего адаптива лаконичнее.
выравнены моменты, на которых "дергается глаз" :)

2022-06-12 22:07 UTC, AvaveryU commented on index.html
> +        <div class="footer__info">
рефакторинг под вариант: **первую группу оставить в 2 строки, а вторую уже в варианте для десктопа**

2022-06-12 22:07 UTC, AvaveryU commented on index.html
> +                    <!--третий список -->
исправлено (одинаковые отступы слева и справа)

2022-06-12 22:07 UTC, AvaveryU commented on index.html
> +        </div>
1 пункт - отступы исправлены
2 пункт - не совсем понятно замечание. Если в новом коммите проблема осталась, просьба пояснить развернутее
3 пункт - исправлена высота блока согласно макету

2022-06-12 22:17 UTC, AvaveryU commented
1. случай атомной войны предусмотрен
2. с размерами логотипов абсолютно согласна, что решение не гибкое. Стояла задача подстроится под макет, в моем представлении мира заказчики могут быть и такими :) Исправила решение, перейдя во-первых на гриды (не совсем нравится своя реализация, но пока "умнее" не придумала), во-вторых слегка отошла в сторону от макета, как раз для более гибкого решения.
3. ссылки согласно стайлгайду были, скрин оттуда о ссылках в футере. при включенной эмуляции устройств в браузере они не отображаются.
![image](https://user-images.githubusercontent.com/88741752/173255782-55fe264a-d80c-48d0-9630-d93f70f97096.png)

2022-06-13 04:17 UTC, olgalatkina commented
решение с гридами отличное🔥
осталось подключить эдиторконфиг и отформатировать код
остальное поправим в конце (отступы снизу иногда возникают)

2022-06-13 04:17 UTC, olgalatkina approved these changes

2022-06-13 12:32 UTC, merged