Feat/header markup
rodiontazetdinov/lubimovka pull request #4
Opened 2022-06-10 05:59 UTC by olgalatkina

ховер на хедере, чтобы посмотреть как будет выглядеть мобильное меню

2022-06-10 21:11 UTC, AvaveryU commented on blocks/header/__logo-link/header__logo-link.css
> +  margin-left: 24px;
имеет смысл ориентироваться на расширенную версию макета, где пункты меню и лого выстраиваются в одну линию (изменить margin-left)
![лого](https://user-images.githubusercontent.com/88741752/173151140-cf50858f-28d4-40f7-900f-10c2eeb3422a.PNG)

2022-06-10 21:14 UTC, AvaveryU commented on index.html
> +        <div class="header__info">
блок относится к footer, а не к header. Либо продумать возможность переиспользования блока из footer. либо, скорее всего, в макете блок footer обозначен только для того, чтобы **визуально** указать разработчикам где должна находится кнопка бургерного меню.

2022-06-10 21:33 UTC, AvaveryU commented on blocks/header/__menu-wrapper/header__menu-wrapper.css
> +.header:hover .header__menu-wrapper {
можно доработать функционал:
1.  после открытия бургерного меню его можно закрыть
2.  после открытия бургерного меню сама иконка заменяется на крестик (его визуал есть на расширенном макете)
![клик](https://user-images.githubusercontent.com/88741752/173154141-e2c1e2ae-f023-4b65-9bd3-f48deea6fd91.png)

2022-06-10 21:38 UTC, AvaveryU commented on blocks/header/__link-wrapper/header__link-wrapper.css
> +  padding: 57px 0 0 56px;
несоответствие макету

2022-06-10 22:06 UTC, AvaveryU requested changes
в целом, работа - супер! Адаптив, плавное появление меню, использование переменных в css - красота.

2022-06-11 03:34 UTC, olgalatkina commented on blocks/header/__logo-link/header__logo-link.css
> +  margin-left: 24px;
заготовлен класс `header__logo_opened-menu,` который добавляется к логотипу при открытии меню

2022-06-11 03:36 UTC, olgalatkina commented on index.html
> +        <div class="header__info">
неожиданно😆 (про указать)
отрефакторим в конце, надо будет продумать, чтобы не отработали стили для планшета и десктопа

2022-06-11 03:37 UTC, olgalatkina commented on blocks/header/__menu-wrapper/header__menu-wrapper.css
> +.header:hover .header__menu-wrapper {
заготовлен класс `burger_close`, по клику добавится на кнопку, отработает анимация

2022-06-12 09:06 UTC, merged